function createfigure_FrequencyResponse(x1,y1,RF_BWFAC,BW_Half,H)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  matrix of y data
 
%  Auto-generated by MATLAB on 04-Jul-2007 11:28:11
 
%% Create figure
if nargin == 5
   figure1 = figure(H);
else
   figure1 = figure;
end
 
%% Create axes
axes1 = axes('FontSize',14,'Parent',figure1);
axis(axes1,[-4000 4000 -1.2 1.2]);
title(axes1,strcat('Frequency Response, Bandwidth factor R= ', num2str(RF_BWFAC)),'Color','r','FontWeight','bold');
xlabel(axes1,'Frequency (Hz)');
ylabel(axes1,'Normalized Magnetization');
box(axes1,'on');
hold(axes1,'all');
 
%% Create multiple lines using matrix input to plot
plot1 = plot(x1,y1);
set(plot1(1),...
  'Color',[0 1 0],...
  'LineWidth',3);
set(plot1(2),...
  'Color',[1 0 0],...
  'LineWidth',3);
set(plot1(3),...
  'Color',[0 0 1],...
  'LineWidth',3);

v = axis;
line([BW_Half(1),BW_Half(1)],[v(3),v(4)],'LineStyle','--','Color','k','LineWidth',2)
line([BW_Half(2),BW_Half(2)],[v(3),v(4)],'LineStyle','--','Color','k','LineWidth',2)
axis([-max(x1) max(x1) -1.2 1.2]) 
%% Create legend
legend1 = legend(axes1,{'Mx','My','Mz'},'FontSize',14);
 
